### ISSUE TITLE
“We were unable to load Disqus" error

### ISSUE THREAD

**Issue by xxks-kkk** [Robpol86/sphinxcontrib-disqus#4]
Hi Robpol86,

I am encountering "We were unable to load Disqus" error when I follow the [usage guide](https://sphinxcontrib-disqus.readthedocs.org/en/latest/). I use [Sphinx-bootstrap-theme](https://github.com/ryan-roemer/sphinx-bootstrap-theme/) and you can find my repo for the web [here](https://github.com/xxks-kkk/xxks-kkk.github.io.source)

I also tried to directly copy universal installation code directly into a html page, and it works.

Do you have clue on why my site not working?

Thanks much!

**Comment by moigagoo** [comment]
I'm having the same issue.

**Comment by xxks-kkk** [comment]
@moigagoo I would recommend [sphinx news feed extension](https://bitbucket.org/zeyuan_hu/sphinxcontrib-newsfeed) if you want to use "disqus" directive. I have tested on my own. It works perfectly.

**Comment by moigagoo** [comment]
@xxks-kkk Thanks! Works like charm!

**Comment by xxks-kkk** [comment]
@moigagoo no problem :smile:

**Comment by godleon** [comment]
@xxks-kkk Thanks! I spent the whole morning trying to integrate with RFD and Disqus. Your information gave me a great help.

**Comment by xxks-kkk** [comment]
@godleon no problem :)
